plot4 <- function(){
  hpc <- read.table('household_power_consumption.txt', header = TRUE, sep = ';', na.strings = '?')
  hpc$Date <- as.Date(hpc$Date, "%d/%m/%Y")
  hpc <- subset(hpc, hpc$Date >= '2007-02-01' & hpc$Date <= '2007-02-02')
  hpc$Global_active_power <- as.numeric(as.character(hpc$Global_active_power))
  hpc$Voltage <- as.numeric(as.character(hpc$Voltage))
  hpc$Global_reactive_power <- as.numeric(as.character(hpc$Global_reactive_power))
  hpc$Time <- paste(hpc$Date, hpc$Time)
  hpc$Time <- strptime(hpc$Time, "%Y-%m-%d %H:%M:%S")
  #par(mfcol = c(2, 2), mar = c(3, 3, 3, 3), oma = c(2, 2, 2, 2))
  par(mfcol = c(2, 2))
  plot(hpc$Time, hpc$Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab="")
  plot(hpc$Time, hpc$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="", col = 'black')
  lines(hpc$Time, hpc$Sub_metering_2, type="l", col = 'red')
  lines(hpc$Time, hpc$Sub_metering_3, type="l", col = 'blue')
  legend('topright',legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), pch='-', col = c('black', 'red', 'blue'), lwd=2, bty="n")
  plot(hpc$Time, hpc$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
  plot(hpc$Time, hpc$Global_reactive_power, type="l", ylab="Global Active Power", xlab="datetime")
  dev.copy(png, width = 480, height = 480, 'plot4.png')
  dev.off()
}